---
- name: Install lsd with Homebrew
  hosts: localhost
  vars:
    dotfile_path: ~/.config
  pre_tasks:
    - name: Create temp directory to house setup files
      ansible.builtin.file:
        path: ~/tmp_installation
        state: directory
        mode: 0775
    - name: Backing up OG dotfiles
      command: mv ~/.config ~/.OGconfig.bak
      when: dotfiles_path.stat.exists is true
  tasks:
    - name: Starship
      community.general.homebrew:
        name: starship
        state: present
    - name: LSD
      community.general.homebrew:
        name: lsd
        state: present
    - name: Bat 
      community.general.homebrew:
        name: bat
        state: present
    - name: Clone dotfiles
      git:
        repo: https://github.com/TheDevArchie/dotfiles.git
        dest: ~/tmp_installation/dotfiles
    - name: Dotfile Setup
      command: mv ~/tmp_installation/dotfiles ~/.config
# Install nerd fonts/FiraCode nerdfont
