# general
import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

#[shell]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.8
blur = true

[scrolling]
multiplier = 1

[font]
normal = { family = "FiraCode Nerd Font" }

[colors]
cursor = {cursor = "#fc8803"}

[bell]

[selection]
semantic_escape_chars = ",│‘|:\"' ()[]{}<>"
save_to_clipboard = true

[cursor]
# BROKEN
style = { shape = "Underline", blinking = "On"}

[terminal]

[mouse]
hide_when_typing = true

[hints]

[keyboard]

[debug]
#render_timer = true
